//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTPLBarcodeDataReceiveSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaminatorBarcodeReaderMappingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaminatorBarcodeReaderMappingMaster()
        {
            this.Transaction_Table = new HashSet<Transaction_Table>();
        }
    
        public int ID { get; set; }
        public int LaminatorID { get; set; }
        public int BarcodeReaderID { get; set; }
        public Nullable<int> DeviceID { get; set; }
    
        public virtual BarcodeReaderMaster BarcodeReaderMaster { get; set; }
        public virtual DeviceMaster DeviceMaster { get; set; }
        public virtual LaminatorMaster LaminatorMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Table> Transaction_Table { get; set; }
    }
}
