//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTPLBarcodeDataReceiveSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaminatorMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaminatorMaster()
        {
            this.LaminatorBarcodeReaderMappingMasters = new HashSet<LaminatorBarcodeReaderMappingMaster>();
        }
    
        public int ID { get; set; }
        public string LaminatorNumber { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaminatorBarcodeReaderMappingMaster> LaminatorBarcodeReaderMappingMasters { get; set; }
    }
}
