//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTPLBarcodeDataReceiveSrvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Table
    {
        public long ID { get; set; }
        public string Module_Serial_Number { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public int LaminatorBarcodeReaderMappingID { get; set; }
        public bool Displayed { get; set; }
        public Nullable<int> ErrorID { get; set; }
        public Nullable<bool> IsErrorResolved { get; set; }
    
        public virtual ErrorCodeMaster ErrorCodeMaster { get; set; }
        public virtual LaminatorBarcodeReaderMappingMaster LaminatorBarcodeReaderMappingMaster { get; set; }
    }
}
